### ISSUE TITLE
Possible to get pixel data of each frame?

### ISSUE THREAD

**Issue by bootsie123** [media-fish/rtmp-server#4]
Hi! I've been playing around with this and I noticed the on data event. I was wondering if it was possible to extract video data from the RTMP stream and then use it to get the frame data. I'm trying to get the pixel data of each frame in order to use it with [node-webrtc](https://github.com/node-webrtc/node-webrtc)

**Comment by kuu** [comment]
Sounds interesting.
The `data` you get is an instance of [AVC](https://github.com/media-fish/flv/blob/master/types.js#L113-L125) and it contains H.264's NAL unit data.
```js
.on('data', ({timestamp, type, data}) => {
  switch (type) {
    case 'video':
      // data is an instance of AVC
      print(data);
      /*
      AVC: {
        frameType: 'keyframe',
        codec: 'AVC',
        packetType: 'NALU',
        data: <Buffer length=1024 >   H.264 NAL unit
      }
      */
      break;
  }
})
```

So, you can extract the encoded video data by accessing the NAL units.
However, to get the pixel data of each frame, you need to decode the data.
I'm not sure if there's any way to do that via JavaScript but you can use C libraries like [x264](https://www.videolan.org/developers/x264.html) as a native addon.

**Comment by kuu** [comment]
I hope the above comment answered your question.
Will close the issue but feel free new one.
