### ISSUE TITLE
Creating audio stream from RTMP stream

### ISSUE THREAD

**Issue by hamzaabamboo** [media-fish/rtmp-server#8]
Hello, I am trying to create an audio stream from a RTMP stream. I am very new with audio codecs and stream. 

What I tried was creating a simple server and stream only select raw audio chunks (I convert the data back to buffer) to a readable stream. But it doesn't work. I saw that the data from createSimpleServer is already serialised to javascript object already.
```
 const readable = new Readable({
    read() {},
  });
 const server = createSimpleServer('/stream');
    server.on('data', message => {
      const { type, data } = message;
      if (type === 'audio') {
        const size = writeData(message.data, null, 0);
        const b = Buffer.alloc(size);
        writeData(message.data, b, 0);
        readable.push(b);
      }
    });
```
How do I combine or concatenate the chunks to create an audio stream ? (to write to a file or stream to other place)

**Comment by kuu** [comment]
Thanks for the comment.
The `message.data` is FLV audio and needs to be wrapped in FLV container.
I wrote a [sample code](https://gist.github.com/kuu/7f3dcf24577ba9a7cc3f4d5496eef21e) to extract the audio from RTMP stream and then store the data as an FLV file (audio.flv)
Please check if it works for you.

**Comment by hamzaabamboo** [comment]
@kuu Thank you for your code ! I modified your code to fit my need to enable continuous stream of audio (to stream in Discord). What I did was just buffer the packets and create small segments of a flv file. I'm not sure whether what I am doing is right or not, but It works and produce audible sound !!

Good library !

```ts
class AudioExtractor extends Transform {
  header: typeof FLVHeader;
  tags: any[];
  start: number;
  wroteHeader = false;
  constructor() {
    super({ objectMode: true });
    this.header = new FLVHeader({
      version: 1,
      hasAudio: true,
      hasVideo: false,
    });
    this.tags = [];
  }

  _transform(obj, _, cb) {
    const { type, timestamp, data } = obj;
    if (type === 'audio') {
      this.tags.push(
        new FLVTag({ type: FLVTag.TagType.audio, timestamp, data }),
      );
      if (!this.start || timestamp - this.start > 750) {
        if (!this.wroteHeader) {
          this.wroteHeader = true;
          const flv = new FLVFile(this.header, this.tags);
          const byteLength = writeData(flv, null, 0);
          const buf = Buffer.alloc(byteLength);
          writeData(flv, buf, 0);
          cb(null, buf);
        } else {
          const byteLength = this.tags
            .map(t => writeData(t, null, 0))
            .reduce((p, c) => p + c, 0);
          const buf = Buffer.alloc(byteLength);
          let offset = 4;
          this.tags.forEach(t => {
            const base = writeData(t, buf, offset);
            offset = writer.writeNumber(base - offset, buf, base, 4);
          });
          cb(null, buf);
        }
        this.tags = [];
        this.start = timestamp;
      } else {
        cb();
      }
    } else {
      cb(null);
    }
  }
}
```
